Feature/homework2
resecmo/python-course-2020 pull request #2
Opened 2020-09-26 19:15 UTC by resecmo

2020-09-26 19:50 UTC, Alvant commented on labs/lab01/main.py
> +s = input()
Этого файла, по-хорошему, в данном реквесте быть не должно было. Его не надо было добавлять через `git add`) либо вы, такое ощущение, отпочковали `feature/homework2` от `feature/homework1`, а не от `master`, и поэтому первая лаба тоже сюда подтянулась. Вообще, смысл веток Гита в том, что в каждой можно делать что-то своё, но потом они все "объединяются" в одной ветке `master`. То есть после создания первого реквеста надо было перейти обратно на `master`: `git checkout master`, создать от мастера новую ветку `feature/homework2` и т.д. Тогда бы `feature/homework2` была бы "чистой", там бы вообще не было бы файлов от первого ДЗ

2020-09-26 19:53 UTC, Alvant commented on labs/lab02/1.sh
> +while True
Питонский True: в Баше он с маленькой буквы `true`

2020-09-26 19:59 UTC, Alvant commented on labs/lab02/1.sh
> +while True
Сверху в скриптах принято писать: шебанг + путь до интерпретатора.
Например
```bash
#!/bin/bash
```
Чтобы узнать, где у вас на машине лежит `bash`, можно выполнить команду в терминале
```bash
which bash
```

2020-09-26 20:04 UTC, Alvant commented on labs/lab02/1.sh
> +  printf "Contents of custom_tmp: %d files, %d folders\n" $f $(($d-1))
А почему `printf`, а не `echo`?) А так ок

2020-09-26 20:06 UTC, Alvant requested changes
Норм, только не очень хорошо, что и первая лаба здесь + True надо поправить

2020-09-27 21:55 UTC, resecmo commented on labs/lab01/main.py
> +s = input()
Да, похоже, что я именно отпочковал ветку со вторым заданием от ветки с первым, но понял это, уже когда запушил, и оставил всё как есть, в следующие разы нормально сделаю.

2020-09-27 22:10 UTC, resecmo commented on labs/lab02/1.sh
> +while True
Исправил
Не понимаю, правда, почему нормально работало и так

2020-09-27 22:11 UTC, resecmo commented on labs/lab02/1.sh
> +while True
Добавил строчку

2020-09-27 22:12 UTC, resecmo commented on labs/lab02/1.sh
> +  printf "Contents of custom_tmp: %d files, %d folders\n" $f $(($d-1))
Хм, ну тут в строку нужно числа вставлять, само получилось)
С `echo`  тоже можно было, конечно

2020-09-30 13:28 UTC, Alvant commented on labs/lab01/main.py
> +s = input()
Ну да, ок) это не страшно. Я тоже считаю, что пару раз в начале допустимо что-то такое сделать, пока вникаешь

2020-09-30 13:29 UTC, Alvant commented on labs/lab02/1.sh
> +  printf "Contents of custom_tmp: %d files, %d folders\n" $f $(($d-1))
Да я ничего) просто интересно было, мб тут была какая-то идея

2020-09-30 13:39 UTC, Alvant commented on labs/lab02/1.sh
> +while True
Да, странно. У меня с `True` работать отказался. Посмотрел примеры: везде тоже с маленькой буквы `true`...

Погуглил немного (https://stackoverflow.com/questions/19670061/bash-if-false-returns-true/47876317#comment29212872_19670094). Говорят, что эти `true`/`false` — это на самом деле команды в терминале https://en.wikipedia.org/wiki/True_and_false_(commands). На Linux-е у меня таких команд, видимо, не было. Но Cmder оболочка, которая на Windows, в самом деле разрешает `True` и `False`.

В общем..) лучше с маленькой буквы. Где-то будет работать и с большой, но не везде.

2020-09-30 13:41 UTC, Alvant commented on labs/lab02/1.sh
> +while True
P.S. Ещё мысль вдогонку: `#!/usr/bin/bash` тоже будет "работать" не на всех машинах. Есть способ, как сделать более универсально, но у него, в свою очередь, есть другие недостатки

2020-09-30 13:42 UTC, Alvant approved these changes

2020-09-30 15:56 UTC, merged